### ISSUE TITLE
Kick Message on Move

### ISSUE THREAD

**Issue by binka-dev** [minecrafter/HubMagic#1]
Hello,

could you add a variable, so that I can add the kick reason to the kicks lead to hub message?

Thank you!
mineyannik

**Comment by minecrafter** [comment]
I can. I've been busy but have the time now.

**Comment by binka-dev** [comment]
Thank you a lot!

**Comment by minecrafter** [comment]
Try this commit.

**Comment by binka-dev** [comment]
Kick leads to hub doesn't work anymore.

**Comment by minecrafter** [comment]
I'll take a look, one second.

**Comment by minecrafter** [comment]
Resolved in 750e1eb
