### ISSUE TITLE
How compile this plugin?

### ISSUE THREAD

**Issue by Sitmobedaf** [minecrafter/HubMagic#3]
How i can compile this plugin? I tried do it in Eclipse, add all components (BungeeCord and lobmok 1.12.2), and i have many errors, for example - " ping.setHost(info.getAddress()); - The method setHost(InetSocketAddress) is undefined for the type ServerListPing"

**Comment by minecrafter** [comment]
You compile this plugin using Maven. For Eclipse, you can use m2e.
